### PR TITLE
Fulfilling zh-TW and zh-CN

### PR DESCRIPTION
**Pull request by maikirakiwi**
Completing both Simplified and Traditional Chinese locales.
* Changed some phrasing from previous -CN commit to more software-oriented terms.

### CODE REVIEW

**Comment by maikirakiwi** [comment]
Just for future reference:
Chinese is a very context-dependent language; thus, L7 and L8 (in both files) cause ambiguity when used under different sections. This is just a temporary locale solution, but I would like to see more fine-grained control over the titles.

**Comment by CanadaHonk** [comment]
Looks good, thanks!

**Comment by CanadaHonk** [comment]
Some small quick things:
 - `zh-TW`'s removing is still in English, is that intentional?
 - Title is old / doesn't matter now anyway since the redesign a week or so ago

**Comment by maikirakiwi** [comment]
> Some small quick things:
> 
> * `zh-TW`'s removing is still in English, is that intentional?
> * Title is old / doesn't matter now anyway since the redesign a week or so ago

Must’ve committed a second too early
I’ll change it in the next commit when more things are available in the json

**Pull request merged**
